AWSTemplateFormatVersion: '2010-09-09'
Description: Reusable Network Infrastructure

Parameters:

  ProjectName:
    Type: String
    Description: Project Name

  VpcCIDR:
    Type: String
    Description: CIDR block for VPC

  PublicSubnet1CIDR:
    Type: String
    Description: CIDR block for Public Subnet 1

  PublicSubnet2CIDR:
    Type: String
    Description: CIDR block for Public Subnet 2

  PrivateSubnet1CIDR:
    Type: String
    Description: CIDR block for Private Subnet 1

  PrivateSubnet2CIDR:
    Type: String
    Description: CIDR block for Private Subnet 2

Resources:

  MyVPC:
    Type: AWS::EC2::VPC

    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc"

  MyInternetGateway:
    Type: AWS::EC2::InternetGateway

    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-igw"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment

    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  PublicSubnet1:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-subnet1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PublicSubnet2CIDR
      MapPublicIpOnLaunch: true

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-subnet2"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnet1CIDR

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-private-subnet1"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet

    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref PrivateSubnet2CIDR

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-private-subnet2"

  PublicRouteTable:
    Type: AWS::EC2::RouteTable

    Properties:
      VpcId: !Ref MyVPC

      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-public-route-table"

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway

    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  PublicSubnet1RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation

    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:

  VPC:
    Description: VPC ID
    Value: !Ref MyVPC
    Export:
      Name: !Sub "${ProjectName}-vpc-id"

  PublicSubnet1:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${ProjectName}-public-subnet1"

  PublicSubnet2:
    Description: Public Subnet 2 ID
    Value: !Ref PublicSubnet2
    Export:
      Name: !Sub "${ProjectName}-public-subnet2"

  PrivateSubnet1:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1
    Export:
      Name: !Sub "${ProjectName}-private-subnet1"

  PrivateSubnet2:
    Description: Private Subnet 2 ID
    Value: !Ref PrivateSubnet2
    Export:
      Name: !Sub "${ProjectName}-private-subnet2"

  PublicSubnets:
    Description: Comma separated list of public subnet IDs
    Value: !Join [",", [!Ref PublicSubnet1, !Ref PublicSubnet2]]

    Export:
      Name: !Sub "${ProjectName}-public-subnets"

  PrivateSubnets:
    Description: Comma separated list of private subnet IDs
    Value: !Join [",", [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]

    Export:
      Name: !Sub "${ProjectName}-private-subnets"